image: node:latest

stages:
  - build
  - deploy

before_script:
  - npm install --force

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    # Add your deployment commands here
